version: "3.9"

services:
  typst-api:
    build:
      context: https://github.com/chinpeerapat/typst-http-api-CJKy.git
      # Usa o Dockerfile do repositório
      pull_policy: build
    container_name: typst-http-api
    environment:
      - PORT=8000
    restart: unless-stopped
    networks:
      - proxy_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy_network:
    external: true
